### ISSUE TITLE
Support for C# SDK v3 

### ISSUE THREAD

**Issue by asleire** [vercel/cosmosdb-server#31]
The C# SDK currently does not work with this CosmosDb server.
NuGet package: https://www.nuget.org/packages/Microsoft.Azure.Cosmos/

I discovered the following issues while attempting to make it work:
- SDK can not be configured to ignore SSL validation errors. My workaround was using reflection to configure the SDK internals
- Addresses endpoint as in https://github.com/zeit/cosmosdb-server/issues/29 is not implemented. Workaround is configuring the C# SDK to use Gateway mode.
- Whenever an error occurs (>399 status code), the C# SDK expects a case sensitive `message` property with non-null value in the response body. Otherwise it will throw a NullReferenceException.
- "Meta" / root endpoint must return certain data, otherwise SDK will throw a NullReferenceException. Additionally the `queryEngineConfiguration` property is required for querying to work.
- The C# parses and validates the _rid property. In particular, it requires RID for collections to have a specific bit set to 1 (first bit of 5th byte)
- A property on `partitionKeyRanges` is invalid, it is `maxInclusive` but should be `maxExclusive`
- C# SDK sends boolean headers with a `"True"` value instead of `"true"`, causing the server to not handle them as true
- C# SDK will query partitionKeys using an "Incremental Feed". See [`A-IM` header](https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-request-headers). Essentially it expects an etag when retrieving partition keys, and it expects a 302 status code once all keys have been received. Current behavior causes an infinite loop in the C# SDK

After forking this repo and applying fixes for the above I am able to successfully use this server with the C# SDK.

I noticed you have a current draft PR with some fixes for the Java SDK, which will fix some of the issues here. I can make a PR with the remaining fixes if you'd like

**Comment by nkzawa** [comment]
Thanks for the detailed report! They all are great findings 😮 

Really appreciate it if you can make the PR. Feel free to reuse some code from https://github.com/zeit/cosmosdb-server/pull/30 if needed.

**Comment by kirankumarkolli** [comment]
For emulator SSL the work-around is covered at https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#running-on-mac-or-linux

**Comment by moredatapls** [comment]
@asleire regarding the SSL issue, you write that your

> workaround was using reflection to configure the SDK internals

Could you explain how you disabled the SSL verification in the client? Thanks a lot!

**Comment by asleire** [comment]
@moredatapls 
I wrote this method for creating a `CosmosClient` with SSL validation disabled: https://gist.github.com/asleire/73fda6b5e80ae4c85b2794470fb46257
It should work with `Microsoft.Azure.Cosmos` package version `3.6.0`

**Comment by asleire** [comment]
I'll close this issue since my PR has been merged. I found more issues regarding advanced queries with the C# client, but basic usage works now
