### ISSUE TITLE
Project has no license file

### ISSUE THREAD

**Issue by shabbyrobe** [vercel/cosmosdb-server#39]
I can't seem to find any detailed license information within this project. The package.json states that the license is MIT, but it would be good for confidence if this was corroborated by a LICENSE file in the project root. Would you mind adding one, or accepting one via a PR?

**Comment by nkzawa** [comment]
Just added the license file, thank for asking!

**Comment by shabbyrobe** [comment]
Wow, that was fast! Thank you!
