### ISSUE TITLE
read-meta hardcoded to port 3000

### ISSUE THREAD

**Issue by lossyrob** [vercel/cosmosdb-server#55]
The read-meta handler [hardcodes port 3000](https://github.com/vercel/cosmosdb-server/blob/45e9f2760a6c4e343d21b62049cc486a9cb5bec9/src/handler/read-meta.ts#L11), which is incorrect when running the server on another port. This causes the Python client to throw a connection refused exception after connecting to a server on another port:

```python
from azure.cosmos import CosmosClient
cosmos = CosmosClient("https://localhost:32797", credential="fake")
 list(cosmos.list_databases())
```

This throws the exception: 

```
 <urllib3.connection.HTTPSConnection object at 0x7fd48863dfd0>: Failed to establish a new connection: [Errno 111] Connection refused
```

due to the client trying to communicate with port 3000, because of the hard coded values.

This can be solved by passing server options to handlers, so that the port can be dynamically generated; this would be a lot of code changes so perhaps there's an easier way to avoid this?

**Comment by nkzawa** [comment]
This should be fixed by https://github.com/vercel/cosmosdb-server/pull/58, released as `0.10.0`. Thanks for your report!
